name: novogene-download
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - Flask==2.0.3
    - Werkzeug==2.0.3
    - Jinja2==3.0.3
    - MarkupSafe==2.0.1
    - click==8.0.4
    - itsdangerous==2.0.1
    - psutil==5.8.0